version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '3000:3000'
    volumes:
      - .:/app 
      - /app/node_modules